#ifndef AWG_EXTENSION_REGS_H
#define AWG_EXTENSION_REGS_H

#define AWG_EXTENSION_AWGX_ID              0x41574758u
#define AWG_EXTENSION_AWGC_ID              0x41574743u
#define AWG_EXTENSION_VERSION              0x00010000u

#define AWG_EXTENSION_REG_ID               0x000u
#define AWG_EXTENSION_REG_VERSION          0x004u
#define AWG_EXTENSION_REG_CAPS             0x008u
#define AWG_EXTENSION_REG_CONTROL          0x00Cu
#define AWG_EXTENSION_REG_STATUS           0x010u
#define AWG_EXTENSION_CONTROL_C1_ENABLE    (1u << 0)
#define AWG_EXTENSION_CONTROL_SOFT_RESET   (1u << 1)

#define AWG_COMPRESSION_REG_ID             0x100u
#define AWG_COMPRESSION_REG_VERSION        0x104u
#define AWG_COMPRESSION_REG_CAPS           0x108u
#define AWG_COMPRESSION_REG_STATUS         0x10Cu
#define AWG_COMPRESSION_REG_ERROR          0x110u
#define AWG_COMPRESSION_REG_RECORDS_LO     0x118u
#define AWG_COMPRESSION_REG_RECORDS_HI     0x11Cu
#define AWG_COMPRESSION_REG_EVENTS_LO      0x120u
#define AWG_COMPRESSION_REG_EVENTS_HI      0x124u
#define AWG_COMPRESSION_REG_BUSY_LO        0x128u
#define AWG_COMPRESSION_REG_BUSY_HI        0x12Cu
#define AWG_COMPRESSION_REG_STALL_LO       0x130u
#define AWG_COMPRESSION_REG_STALL_HI       0x134u
#define AWG_COMPRESSION_REG_CRC_LO         0x138u
#define AWG_COMPRESSION_REG_CRC_HI         0x13Cu
#define AWG_COMPRESSION_REG_DECLARED_LO    0x140u
#define AWG_COMPRESSION_REG_DECLARED_HI    0x144u
#define AWG_COMPRESSION_REG_MAX_DEPTH      0x148u
#define AWG_COMPRESSION_REG_MAX_COMMANDS   0x14Cu

#endif
